//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akron.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ProductoId { get; set; }
        public string ProductoCodigo { get; set; }
        public string ProductoNombre { get; set; }
        public string ProductoDescripcion { get; set; }
        public string ProductoPropBene { get; set; }
        public string ProductoEspecificacion { get; set; }
        public string ProductoRecomUso { get; set; }
        public string ProductoCaracteristicas { get; set; }
        public string ProductoDisponible { get; set; }
        public string ProductoImagen { get; set; }
        public string ProductoImagenFolleto { get; set; }
        public string ProductoFichaTecnica { get; set; }
        public string ProductoHojaseguridad { get; set; }
        public string ProductoTestimonial { get; set; }
        public string ProductoCertificacion { get; set; }
        public string ProductoMarca { get; set; }
        public byte ProductoStatus { get; set; }
    }
}
